[package]
name = "dbg-macro"
# if you use git repo, package version is git
version = "git"
description = "Forked: A dbg(â€¦) macro for C++"
global=false
# library name in cmake, cppm.toml use this value 
# [dependencies]
#${library_name} = {module =${value}}
cmake = {name = "dbg-macro::dbg-macro", findlib=""}
# write download value git or url
download = {git="https://github.com/injae/dbg-macro.git"}
#download = {url=""}
